FROM debian:bookworm-slim

# Instalação do Apache, MySQL e PHP
RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y apache2 mariadb-server php php-mysql \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

# Expor a porta do Apache (padrão: 80)
EXPOSE 80

# Comando para iniciar o Apache em primeiro plano
CMD ["apachectl","-D","FOREGROUND"]
