FROM debian:bookworm-slim
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y openssh-server && apt clean && rm -rf /var/lib/apt/lists/*
RUN mkdir /var/run/sshd
RUN echo "root:calangos" | chpasswd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"] 
