FROM debian:bookworm-slim

# Instalação do servidor SSh
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configuração do servidor SSH
RUN mkdir /var/run/sshd

# Configurar a senha para o usuário root (substituir 'password' pela senha desejada)
RUN echo 'root:password' | chpasswd

# Expor a porta SSH (porta 22)
EXPOSE 22

# Comando para iniciar o servidor SSH
CMD ["/usr/sbin/sshd", "-D"]
