FROM debian:latest
LABEL maintainer="Cristian Alves <cristian@gmail.com>"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get -y install apache2 \
    && apt-get clean \
    && a2enmod proxy \
    && a2enmod proxy_http \
    && a2enmod ssl \
    && a2enmod rewrite \
    && service apache2 stop
EXPOSE 80
VOLUME /etc/apache2/sites-available
COPY configs/httpd.conf /etc/apache2/sites-available/000-default.conf
CMD ["apachectl", "-D", "FOREGROUND"]
