FROM debian:latest

RUN apt-get update && apt-get install -y proftpd-basic openssh-client

RUN echo "LoadModule mod_sftp.c" >> /etc/proftpd/modules.conf

RUN echo "<IfModule mod_sftp.c>    SFTPEngine on    Port 2222    SFTPLog /var/log/proftpd/sftp.log    SFTPHostKey /etc/ssh/ssh_host_rsa_key    SFTPHostKey /etc/ssh/ssh_host_dsa_key    SFTPHostKey /etc/ssh/ssh_host_ecdsa_key    SFTPHostKey /etc/ssh/ssh_host_ed25519_key    SFTPAuthMethods password</IfModule>" >> /etc/proftpd/proftpd.conf

RUN mkdir -p /etc/ssh &&     ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' &&     ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N '' &&     ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' &&     ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''

RUN useradd -m cristian && echo "cristian:calangos" | chpasswd

EXPOSE 2222

CMD ["/usr/sbin/proftpd", "-n"]
