FROM debian:bookworm-slim

# Instalação do Samba

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y samba && apt-get clean && rm -rf /var/lib/apt/lists/*

# Expor as portas necessárias
EXPOSE 137/udp 138/udp 139 445

# Copiar o arquivo de configuração do Samba
COPY smb.conf /etc/samba/smb.conf

# Criar um volume para compartilhamento de arquivos
VOLUME /samba

# Comando para iniciar o servidor Samba
CMD ["smbd", "--foreground", "--no-process-group"]
